version: '3.8'

services:
  # Application frontend and API
  documind:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "${DOCUMIND_PORT:-8080}:8080"
    volumes:
      - documind-storage:/var/documind/storage
    depends_on:
      - db
    env_file: .env
    environment:
      - NODE_ENV=production
      - DOCUMIND_DATABASE_SERVER=db:5432
    networks:
      - documind-network
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Database - PostgreSQL by default
  db:
    image: ${DOCUMIND_DATABASE_IMAGE:-postgres:14-alpine}
    restart: always
    volumes:
      - documind-db-data:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_USER=${DOCUMIND_DATABASE_USER:-documind}
      - POSTGRES_PASSWORD=${DOCUMIND_DATABASE_PASSWORD:-documind}
      - POSTGRES_DB=${DOCUMIND_DATABASE_NAME:-documind}
      - MYSQL_USER=${DOCUMIND_DATABASE_USER:-documind}
      - MYSQL_PASSWORD=${DOCUMIND_DATABASE_PASSWORD:-documind}
      - MYSQL_DATABASE=${DOCUMIND_DATABASE_NAME:-documind}
      - MYSQL_ROOT_PASSWORD=${DOCUMIND_DATABASE_PASSWORD:-documind}
    networks:
      - documind-network
    healthcheck:
      test: ${DOCUMIND_DATABASE_HEALTH_CMD:-["CMD", "pg_isready", "-U", "documind"]}
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  # Nginx for SSL termination and serving static assets
  web:
    image: nginx:alpine
    restart: always
    ports:
      - "${DOCUMIND_WEB_PORT:-80}:80"
      - "${DOCUMIND_WEB_SSL_PORT:-443}:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - documind-storage:/var/documind/storage:ro
    depends_on:
      - documind
    networks:
      - documind-network
    environment:
      - NGINX_PORT=${DOCUMIND_WEB_PORT:-80}
      - NGINX_SSL_PORT=${DOCUMIND_WEB_SSL_PORT:-443}
      - DOCUMIND_SERVICE=documind:8080

  # Automated backup service
  backup:
    build:
      context: ./docker/backup
    restart: always
    volumes:
      - documind-storage:/var/documind/storage:ro
      - documind-backups:/backups
    depends_on:
      - db
    networks:
      - documind-network
    environment:
      - BACKUP_RETENTION_DAYS=7
      - BACKUP_SCHEDULE=${DOCUMIND_BACKUP_SCHEDULE:-0 2 * * *}
      - DOCUMIND_DATABASE_DRIVER=${DOCUMIND_DATABASE_DRIVER:-postgres}
      - DOCUMIND_DATABASE_SERVER=db:5432
      - DOCUMIND_DATABASE_USER=${DOCUMIND_DATABASE_USER:-documind}
      - DOCUMIND_DATABASE_PASSWORD=${DOCUMIND_DATABASE_PASSWORD:-documind}
      - DOCUMIND_DATABASE_NAME=${DOCUMIND_DATABASE_NAME:-documind}

volumes:
  documind-storage:
    driver: local
  documind-db-data:
    driver: local
  documind-backups:
    driver: local

networks:
  documind-network:
    driver: bridge
