version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: documind-app
    restart: unless-stopped
    ports:
      - "${DOCUMIND_PORT:-8080}:8080"
    volumes:
      - documind-storage:/var/documind/storage
      - documind-data:/var/documind/data
      - ./.env:/app/.env:ro
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: ${DOCUMIND_DATABASE_IMAGE:-postgres:14-alpine}
    container_name: documind-db
    restart: unless-stopped
    volumes:
      - documind-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DOCUMIND_DATABASE_USER:-documind}
      - POSTGRES_PASSWORD=${DOCUMIND_DATABASE_PASSWORD:-documind}
      - POSTGRES_DB=${DOCUMIND_DATABASE_NAME:-documind}
    healthcheck:
      test: ${DOCUMIND_DATABASE_HEALTH_CMD:-["CMD", "pg_isready", "-U", "documind"]}
      interval: 10s
      timeout: 5s
      retries: 5

  webdav:
    image: bytemark/webdav
    container_name: documind-webdav
    restart: unless-stopped
    ports:
      - "${DOCUMIND_WEBDAV_PORT:-1900}:80"
    environment:
      - AUTH_TYPE=Basic
      - USERNAME=${DOCUMIND_WEBDAV_USERNAME:-documind}
      - PASSWORD=${DOCUMIND_WEBDAV_PASSWORD:-documind}
    volumes:
      - documind-storage:/var/lib/dav/data
    depends_on:
      - app

  backup:
    build:
      context: ./docker/backup
      dockerfile: Dockerfile
    container_name: documind-backup
    restart: unless-stopped
    volumes:
      - documind-storage:/var/documind/storage:ro
      - documind-data:/var/documind/data:ro
      - documind-db:/var/lib/postgresql/data:ro
      - ./backups:/backups
    environment:
      - DOCUMIND_DATABASE_DRIVER=${DOCUMIND_DATABASE_DRIVER:-postgres}
      - DOCUMIND_DATABASE_SERVER=db:${DOCUMIND_DATABASE_SERVER_PORT:-5432}
      - DOCUMIND_DATABASE_USER=${DOCUMIND_DATABASE_USER:-documind}
      - DOCUMIND_DATABASE_PASSWORD=${DOCUMIND_DATABASE_PASSWORD:-documind}
      - DOCUMIND_DATABASE_NAME=${DOCUMIND_DATABASE_NAME:-documind}
      - BACKUP_RETENTION_DAYS=${DOCUMIND_BACKUP_RETENTION_DAYS:-30}
      - BACKUP_SCHEDULE=${DOCUMIND_BACKUP_SCHEDULE:-0 2 * * *}
    depends_on:
      - db
      - app

  nginx:
    image: nginx:alpine
    container_name: documind-nginx
    restart: unless-stopped
    ports:
      - "${DOCUMIND_WEB_PORT:-80}:80"
      - "${DOCUMIND_WEB_SSL_PORT:-443}:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
      - webdav
    environment:
      - DOCUMIND_DOMAIN=${DOCUMIND_DOMAIN:-localhost}

volumes:
  documind-storage:
  documind-data:
  documind-db:
