version: '3'

services:
  # Main Documind application
  documind:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: documind
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DOCUMIND_DATABASE_DRIVER=${DOCUMIND_DATABASE_DRIVER:-postgres}
      - DOCUMIND_DATABASE_SERVER=db:5432
      - DOCUMIND_DATABASE_USER=${DOCUMIND_DATABASE_USER:-documind}
      - DOCUMIND_DATABASE_PASSWORD=${DOCUMIND_DATABASE_PASSWORD:-documind}
      - DOCUMIND_DATABASE_NAME=${DOCUMIND_DATABASE_NAME:-documind}
      - DOCUMIND_AUTH_MODE=${DOCUMIND_AUTH_MODE:-password}
      - DOCUMIND_STORAGE_PATH=/var/documind/storage
      - DOCUMIND_STORAGE_MAX_SIZE=${DOCUMIND_STORAGE_MAX_SIZE:-10240}
      - DOCUMIND_INDEXING_THREADS=${DOCUMIND_INDEXING_THREADS:-2}
      - DOCUMIND_ENABLE_OCR=${DOCUMIND_ENABLE_OCR:-true}
      - DOCUMIND_ENABLE_NLP=${DOCUMIND_ENABLE_NLP:-true}
      - DOCUMIND_CACHE_SIZE=${DOCUMIND_CACHE_SIZE:-1024}
    volumes:
      - documind-storage:/var/documind/storage
    depends_on:
      - db
    networks:
      - documind-network

  # Database
  db:
    image: postgres:14-alpine
    container_name: documind-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DOCUMIND_DATABASE_USER:-documind}
      - POSTGRES_PASSWORD=${DOCUMIND_DATABASE_PASSWORD:-documind}
      - POSTGRES_DB=${DOCUMIND_DATABASE_NAME:-documind}
    volumes:
      - documind-db-data:/var/lib/postgresql/data
    networks:
      - documind-network

  # Redis for caching and task queue
  redis:
    image: redis:alpine
    container_name: documind-redis
    restart: unless-stopped
    volumes:
      - documind-redis-data:/data
    networks:
      - documind-network

  # Elasticsearch for advanced search (optional)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: documind-elasticsearch
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - documind-es-data:/usr/share/elasticsearch/data
    networks:
      - documind-network
    profiles:
      - full # Only start with 'docker-compose --profile full up'

  # Nginx for reverse proxy and TLS termination
  nginx:
    image: nginx:alpine
    container_name: documind-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - documind-storage:/var/documind/storage:ro # For direct download of large files
    depends_on:
      - documind
    networks:
      - documind-network
    profiles:
      - full # Only start with 'docker-compose --profile full up'

volumes:
  documind-storage:
  documind-db-data:
  documind-redis-data:
  documind-es-data:


networks:
  documind-network:
